"""add minimum_score to missions and quest_assignments

Revision ID: 8191ebab35ec
Revises: 5abba966b78a
Create Date: 2026-09-30 09:00:00.000000

Stage 2 — Performance-Aware Readiness. Purely additive: two nullable
NUMERIC columns, no constraints, no index changes, no data backfill.
Every existing row gets NULL, which readiness_service.py treats as
"completion is sufficient" — the exact pre-Stage-2 behavior — so this
migration cannot change any existing employee's readiness state on its
own; a manager has to explicitly opt a Mission/QuestAssignment into a
real threshold afterward.

Hand-written, not autogenerated: this sandbox has no reachable
PostgreSQL instance to run `alembic revision --autogenerate` against
(this project's alembic/env.py deliberately refuses to target SQLite —
see its own module docstring), so this file was written to match
`app/models/mission.py`'s and `app/models/quest_assignment.py`'s actual
`minimum_score: Mapped[float | None] = mapped_column(Numeric, nullable=True)`
declarations exactly, and to match this project's existing
autogenerated migrations' style (see 8a1e5ac24b5e/5abba966b78a) as
closely as a hand-written file can.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8191ebab35ec'
down_revision: Union[str, None] = '5abba966b78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('missions', sa.Column('minimum_score', sa.Numeric(), nullable=True))
    op.add_column('quest_assignments', sa.Column('minimum_score', sa.Numeric(), nullable=True))


def downgrade() -> None:
    op.drop_column('quest_assignments', 'minimum_score')
    op.drop_column('missions', 'minimum_score')
