"""initial schema

Revision ID: e094cc980cc4
Revises: 
Create Date: 2026-09-29 12:57:12.833571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e094cc980cc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('departments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_integrations',
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_ref', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('workspace_link', sa.String(length=1000), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id')
    )
    op.create_table('employees',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('identity_provider', sa.String(length=50), nullable=True),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('uq_employee_external_identity', 'employees', ['identity_provider', 'external_subject'], unique=True, sqlite_where=sa.text('identity_provider IS NOT NULL AND external_subject IS NOT NULL'), postgresql_where=sa.text('identity_provider IS NOT NULL AND external_subject IS NOT NULL'))
    op.create_table('missions',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission_type', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('workspace_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_profiles',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'capability_id', name='uq_capability_profile_employee_capability')
    )
    op.create_table('employee_invitations',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_employee_invitation_active', 'employee_invitations', ['employee_id'], unique=True, sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
    op.create_index('uq_employee_invitation_token_hash', 'employee_invitations', ['token_hash'], unique=True)
    op.create_table('mission_attempts',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_service', sa.String(length=120), nullable=True),
    sa.Column('likely_cause', sa.String(length=120), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence_viewed', sa.JSON(), nullable=False),
    sa.Column('quiz_answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'employee_id', name='uq_mission_attempt_mission_employee')
    )
    op.create_table('onboarding_sessions',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('current_scene', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_onboarding_session_employee')
    )
    op.create_table('quests',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_employee_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.String(length=30), nullable=False),
    sa.Column('workspace_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_access_grants',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_integration_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_ref', sa.String(length=500), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'workspace_integration_id', name='uq_workspace_access_grant_employee_integration')
    )
    op.create_table('assessments',
    sa.Column('onboarding_session_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_assignments',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('onboarding_session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_assignments',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(assignment_type = 'EMPLOYEE' AND employee_id IS NOT NULL AND department_id IS NULL AND role_id IS NULL) OR (assignment_type = 'DEPARTMENT' AND department_id IS NOT NULL AND employee_id IS NULL AND role_id IS NULL) OR (assignment_type = 'ROLE' AND role_id IS NOT NULL AND employee_id IS NULL AND department_id IS NULL)", name='ck_quest_assignment_single_target'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_quest_assignment_department', 'quest_assignments', ['quest_id', 'department_id'], unique=True, sqlite_where=sa.text("assignment_type = 'DEPARTMENT'"), postgresql_where=sa.text("assignment_type = 'DEPARTMENT'"))
    op.create_index('uq_quest_assignment_employee', 'quest_assignments', ['quest_id', 'employee_id'], unique=True, sqlite_where=sa.text("assignment_type = 'EMPLOYEE'"), postgresql_where=sa.text("assignment_type = 'EMPLOYEE'"))
    op.create_index('uq_quest_assignment_role', 'quest_assignments', ['quest_id', 'role_id'], unique=True, sqlite_where=sa.text("assignment_type = 'ROLE'"), postgresql_where=sa.text("assignment_type = 'ROLE'"))
    op.create_table('quest_attempts',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission', sa.JSON(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'employee_id', name='uq_quest_attempt_quest_employee')
    )
    op.create_table('quest_capabilities',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'capability_id', name='uq_quest_capability_quest_capability')
    )
    op.create_table('quest_evaluation_criteria',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criterion_type', sa.String(length=20), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('reference_solution', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Numeric(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_evidence',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_tasks',
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('quest_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('target_capabilities', sa.JSON(), nullable=False),
    sa.Column('capability_snapshot', sa.JSON(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_employee_created', 'recommendations', ['employee_id', 'created_at'], unique=False)
    op.create_index('idx_recommendations_employee_type_created', 'recommendations', ['employee_id', 'recommendation_type', 'created_at'], unique=False)
    op.create_index('idx_recommendations_quest', 'recommendations', ['quest_id'], unique=False)
    op.create_table('capability_evaluations',
    sa.Column('mission_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('quest_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('evaluation_version', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('structured_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('(mission_attempt_id IS NOT NULL AND quest_attempt_id IS NULL) OR (mission_attempt_id IS NULL AND quest_attempt_id IS NOT NULL)', name='ck_capability_evaluation_single_attempt'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_attempt_id'], ['mission_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_attempt_id'], ['quest_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_capability_evaluation_mission_attempt', 'capability_evaluations', ['mission_attempt_id'], unique=True, sqlite_where=sa.text('mission_attempt_id IS NOT NULL'), postgresql_where=sa.text('mission_attempt_id IS NOT NULL'))
    op.create_index('uq_capability_evaluation_quest_attempt', 'capability_evaluations', ['quest_attempt_id'], unique=True, sqlite_where=sa.text('quest_attempt_id IS NOT NULL'), postgresql_where=sa.text('quest_attempt_id IS NOT NULL'))
    op.create_table('capability_evidence',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('mission_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('quest_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('(mission_attempt_id IS NOT NULL AND quest_attempt_id IS NULL) OR (mission_attempt_id IS NULL AND quest_attempt_id IS NOT NULL)', name='ck_capability_evidence_single_attempt'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['capability_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_attempt_id'], ['mission_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_attempt_id'], ['quest_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capability_evidence')
    op.drop_index('uq_capability_evaluation_quest_attempt', table_name='capability_evaluations', sqlite_where=sa.text('quest_attempt_id IS NOT NULL'), postgresql_where=sa.text('quest_attempt_id IS NOT NULL'))
    op.drop_index('uq_capability_evaluation_mission_attempt', table_name='capability_evaluations', sqlite_where=sa.text('mission_attempt_id IS NOT NULL'), postgresql_where=sa.text('mission_attempt_id IS NOT NULL'))
    op.drop_table('capability_evaluations')
    op.drop_index('idx_recommendations_quest', table_name='recommendations')
    op.drop_index('idx_recommendations_employee_type_created', table_name='recommendations')
    op.drop_index('idx_recommendations_employee_created', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('quest_tasks')
    op.drop_table('quest_evidence')
    op.drop_table('quest_evaluation_criteria')
    op.drop_table('quest_capabilities')
    op.drop_table('quest_attempts')
    op.drop_index('uq_quest_assignment_role', table_name='quest_assignments', sqlite_where=sa.text("assignment_type = 'ROLE'"), postgresql_where=sa.text("assignment_type = 'ROLE'"))
    op.drop_index('uq_quest_assignment_employee', table_name='quest_assignments', sqlite_where=sa.text("assignment_type = 'EMPLOYEE'"), postgresql_where=sa.text("assignment_type = 'EMPLOYEE'"))
    op.drop_index('uq_quest_assignment_department', table_name='quest_assignments', sqlite_where=sa.text("assignment_type = 'DEPARTMENT'"), postgresql_where=sa.text("assignment_type = 'DEPARTMENT'"))
    op.drop_table('quest_assignments')
    op.drop_table('mission_assignments')
    op.drop_table('assessments')
    op.drop_table('workspace_access_grants')
    op.drop_table('quests')
    op.drop_table('onboarding_sessions')
    op.drop_table('mission_attempts')
    op.drop_index('uq_employee_invitation_token_hash', table_name='employee_invitations')
    op.drop_index('uq_employee_invitation_active', table_name='employee_invitations', sqlite_where=sa.text('used_at IS NULL AND revoked_at IS NULL'), postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
    op.drop_table('employee_invitations')
    op.drop_table('capability_profiles')
    op.drop_table('missions')
    op.drop_index('uq_employee_external_identity', table_name='employees', sqlite_where=sa.text('identity_provider IS NOT NULL AND external_subject IS NOT NULL'), postgresql_where=sa.text('identity_provider IS NOT NULL AND external_subject IS NOT NULL'))
    op.drop_table('employees')
    op.drop_table('workspace_integrations')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('departments')
    op.drop_table('organizations')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
